tap "cloudflare/cloudflare"

# Language and version managers (rbenv, tfenv, go, yarn, etc.) are omitted —
# they are managed by mise. See dot_config/mise/config.toml.
#
# chezmoi is omitted — it must be installed BEFORE running chezmoi init --apply.
# See README.md for bootstrap instructions.

brew "tree"
brew "ansible"
brew "awscli"
brew "bat"
brew "bat-extras"
brew "checkov"
brew "cloudflared"
brew "curl"
brew "direnv"
brew "dive"
brew "eza"
brew "fzf"
brew "gh"
brew "git-extras"
brew "helm"
brew "htop"
brew "jq"
brew "k9s"
brew "kubernetes-cli"
brew "krew"
brew "kubectx"
brew "kustomize"
brew "librsvg"
brew "mise"
brew "mosh"
brew "neovim"
brew "nmap"
brew "pandoc"
brew "pkgconf"
brew "pre-commit"
brew "ripgrep"
brew "ripgrep-all"
brew "starship"
brew "stern"
brew "testdisk"
brew "tmux"
brew "trivy"
brew "uv"
brew "watch"
brew "watchman"
brew "wget"
brew "yq"
brew "zoxide"

cask "caffeine"
cask "font-monaspace"
cask "ghostty"
cask "vlc"

vscode "4ops.terraform"
vscode "anthropic.claude-code"
vscode "bierner.markdown-mermaid"
vscode "cstuder.gitlab-ci-validator"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "ftonato.password-generator"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "m4ns0ur.base64"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode.powershell"
vscode "piotrpalarz.vscode-gitignore-generator"
vscode "pkief.material-icon-theme"
vscode "pomber.git-file-history"
vscode "renkun.reader"
vscode "repreng.csv"
vscode "samuelcolvin.jinjahtml"
vscode "seyyedkhandon.gpack"
vscode "tamasfe.even-better-toml"
vscode "the0807.uv-toolkit"
vscode "tomoki1207.pdf"
vscode "yzhang.markdown-all-in-one"
uv "ruff"
